services:
  - docker

before_install:
  - docker pull microsoft/mssql-server-linux:latest
  - docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=P@ssw0rd1' -h mydb -p 1433:1433 --name mssqldb -d microsoft/mssql-server-linux
  - sleep 90
  - docker exec -t mssqldb /opt/mssql-tools/bin/sqlcmd -S mydb -U SA -P 'P@ssw0rd1' -Q "CREATE DATABASE rsqlserverdb;"

install:
  - docker build -t rsqlserver .

script:
  - docker run -t --link=mssqldb --name pkgcheck rsqlserver Rscript -e 'devtools::install_dev_deps("."); devtools::check(document = FALSE, check_dir = ".")'
  - docker cp pkgcheck:/usr/local/R/rsqlserver.Rcheck/00check.log .
  - if cat 00check.log | grep -q ERROR ; then exit 1; fi
  # Choose to fail if warnings are present in R CMD CHECK (comment this out for now)
  #- if cat 00check.log | grep -q WARNING ; then exit 1; fi
  - exit 0
